### ISSUE TITLE
Update Syntax for Swift 3.0

### ISSUE THREAD

**Issue by StephenClarkApps** [vermont42/RaceRunner#1]
Multiple updates to syntax etc required to enable this code to function correctly.

**Comment by vermont42** [comment]
@StephenClarkApps Can you point to a specific instance of syntax needing updating? I have updated to Swift 3 and pushed those changes. To verify, I just took the following steps:

1. verified that `git status` shows no uncommitted changes
2. cleaned, built, and ran with no code-related warnings in Xcode 8.2.1

That said, I see 84 warnings from Interface Builder about frame positions being different at runtime. This is not surprising because I saw the same thing happen when my app [Immigration](http://www.immigrationapp.biz) transitioned from Xcode 7 to 8. This causes me not to want to use Interface Builder for my next app.

**Comment by vermont42** [comment]
Not having heard from you about how syntax needs to be updated, I am closing this issue.
